// GPL compliance kit builders (spec: "Packaging & release" — libsidplayfp
// pattern). Called by tools/package/build-package.mjs.

import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PRUNE = new Set([
  ".git",
  ".github",
  ".vs",
  "bin",
  "obj",
  "node_modules",
  "artifacts",
  "_docs",
  "test-results",
  "playwright-report",
  "TestResults",
]);

/**
 * Builds the GPLv3 §3a Corresponding Source tarball:
 * this repo's tracked tree at HEAD plus the full vendored upstream subtree.
 */
export function buildCompleteSource(root, outFile) {
  const staging = join(root, "artifacts", "pkg-src-staging");
  rmSync(staging, { recursive: true, force: true });
  mkdirSync(staging, { recursive: true });

  const archiveTar = join(root, "artifacts", "pkg-src-head.tar");
  run("git", ["archive", "--format=tar", "--output", archiveTar, "HEAD"], root);
  run("tar", ["-xf", archiveTar, "-C", staging], root);
  rmSync(archiveTar, { force: true });

  const everywhereSrc = join(root, "external", "PKHeX.Everywhere");
  if (!existsSync(everywhereSrc)) {
    throw new Error("vendored submodule external/PKHeX.Everywhere is not checked out");
  }
  cpSync(everywhereSrc, join(staging, "external", "PKHeX.Everywhere"), {
    recursive: true,
    filter: (src) => !PRUNE.has(partAt(src, root)),
  });

  prune(staging);
  mkdirSync(join(staging, "artifacts"), { recursive: true });
  mkdirSync(root, { recursive: true });
  run("tar", ["-czf", outFile, "-C", staging, "."], root);
  rmSync(staging, { recursive: true, force: true });
}

function run(cmd, args, cwd) {
  const res = spawnSync(cmd, args, { cwd, stdio: "inherit" });
  if (res.status !== 0) throw new Error(`${cmd} ${args.join(" ")} exited ${res.status}`);
}

/** Path segment directly under `root` for `path`, or null when outside. */
function partAt(path, root) {
  const rel = path.slice(root.length).replace(/\\/g, "/").replace(/^\//, "");
  return rel.includes("/") ? null : rel;
}

function prune(dir) {
  for (const name of readdirSync(dir)) {
    const child = join(dir, name);
    if (!PRUNE.has(name)) {
      try {
        if (readdirSync(child)) prune(child);
      } catch {
        /* file */
      }
      continue;
    }
    rmSync(child, { recursive: true, force: true });
  }
}

export function writeUpstreamJson(stage, pins) {
  const upstream = {
    $comment: "Vendored upstream pins for pkhex-wasm. Regenerated by tools/package/build-package.mjs.",
    pkhexEverywhere: {
      url: "https://github.com/arleypadua/PKHeX.Everywhere.git",
      commit: pins.everywhere,
      license: "MIT",
      role: "vendored upstream monorepo hosting the PKHeX fork as a nested submodule",
    },
    pkhexCoreFork: {
      url: "https://github.com/arleypadua/PKHeX",
      commit: pins.fork,
      license: "GPL-3.0-or-later",
      role: "PKHeX.Core sources compiled into the shipped wasm bundle",
      vendoredCrypto: {
        source: "https://github.com/bcgit/bc-csharp",
        commit: "214b5f881be55d708e528ae43693a70211557075",
        license: "MIT",
        provenanceDoc: "src/PKHexWasm/Crypto/Vendored/PROVENANCE.md (in complete-source.tar.gz)",
      },
    },
    generatedAt: new Date().toISOString(),
  };
  writeFileSync(join(stage, "upstream.json"), `${JSON.stringify(upstream, null, 2)}\n`);
}
