/**
 * Emitter B (v2) — the importable entity-type module.
 *
 * Renders the shared projection into a real (non-ambient) TypeScript module:
 *
 *   src/ts/gen/v2/entities.ts
 *
 * Where the .d.ts describes the eventual package surface, this module gives
 * implementation sessions (#36 binding work) an importable type vocabulary
 * today. Types only: narrowing guards and static surfaces arrive with their
 * runtime implementations. Perpetually generated; never hand-edited.
 */

import {
  capFirst,
  projectCoreMeta,
  type ProjectedCoreModel,
} from "./project.ts";
import type { CoreMetaLike } from "./meta-types.ts";

export const V2_ENTITIES_PATH = "src/ts/gen/v2/entities.ts";

export function emitV2Entities(meta: CoreMetaLike): {
  path: typeof V2_ENTITIES_PATH;
  content: string;
} {
  const model = projectCoreMeta(meta);
  return { path: V2_ENTITIES_PATH, content: renderEntities(model) };
}

function renderEntities(model: ProjectedCoreModel): string {
  const lines: string[] = [];

  lines.push("/**");
  lines.push(" * Projected v2 entity types.");
  lines.push(" *");
  lines.push(` * Covers ${model.stats.classes} classes / ${model.stats.members} members / ${model.enums.length} enums`);
  lines.push(` * (${model.stats.shadowed} ancestor-shadowed redeclarations suppressed).`);
  lines.push(" *");
  lines.push(" * @generated by tools/apigen — regenerate with `deno task gen`; do not edit.");
  lines.push(" */");
  lines.push("");

  for (const e of model.enums) {
    lines.push(`export type ${e.name} = ${e.union};`);
    lines.push("");
  }

  for (const cls of model.classes) {
    if (cls.kind === "static") continue; // functions land with their runtime impl
    if (cls.entityContext || cls.kind !== "class") {
      const ctx = cls.entityContext ? ` (${cls.entityContext})` : "";
      lines.push(`/** ${cls.kind}${ctx}, projected from \`${cls.fqn}\`. */`);
    }
    const ext = cls.extends ? ` extends ${cls.extends}` : "";
    lines.push(`export interface ${cls.name}${ext} {`);
    for (const member of cls.members) {
      if (member.isStatic || member.shadowed) continue;
      if (member.docs) lines.push(`  /** ${member.docs} */`);
      if (member.kind === "method") {
        const params = member.params.map((p) => `${p.name}: ${p.tsType}`).join(", ");
        lines.push(`  ${member.tsName}(${params}): ${member.tsType};`);
      } else {
        lines.push(`  readonly ${member.tsName}: ${member.tsType};`);
        if (member.setter) {
          lines.push(`  set${capFirst(member.tsName)}(value: ${member.tsType}): void;`);
        }
      }
    }
    lines.push("}");
    lines.push("");
  }

  if (model.unresolved.length > 0) {
    lines.push("// Named types outside the scanned class set resolve as unknown until");
    lines.push("// the reflector's projection scope widens to cover them.");
    for (const name of model.unresolved) {
      lines.push(`export type ${name} = unknown;`);
    }
    lines.push("");
  }

  return lines.join("\n") + "\n";
}
